name: Release EXE

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # conda-forge 環境（Python 3.10）
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: build
          miniforge-version: latest
          channels: conda-forge
          use-mamba: true
          python-version: "3.10"

      - name: Toolchain & deps (FINAL)
        shell: bash -l {0}
        run: |
          # Fortran は保険（wfnsympy 等のソースビルドに備え）
          mamba install -y fortran-compiler pip
          python -V
          which python

          # ★ここが肝★ 先に「pip」で NumPy<2 / SciPy / setuptools<60 を入れる
          python -m pip install -U "numpy<2" "scipy==1.10.1" "setuptools<60" wheel
          python -m pip show numpy setuptools

          # huckelpy は古い setup.py（numpy.distutils）前提 → build isolation を切る
          PIP_NO_BUILD_ISOLATION=1 python -m pip install --no-use-pep517 "huckelpy==0.2.3"

          # cosymlib は cp310 の wheel を使わせる（ソースビルド禁止）
          python -m pip install --only-binary=:all: "cosymlib==0.11.1"

          # GUI/パッカー
          python -m pip install -U "flet[all]==0.28.3" pyinstaller

      - name: Pack with Flet (PyInstaller)
        shell: bash -l {0}
        run: |
          python -m flet pack src/shape_measure/gui.py --name "Easy Shape" --icon assets/icon.ico
          ls -R dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**
