name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # conda-forge ベースの環境
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: build
          miniforge-version: latest
          channels: conda-forge
          use-mamba: true
          python-version: "3.10"

      - name: Toolchain & pins
        shell: bash -l {0}
        run: |
          # Fortran は念のため（wfnsympy/huckelpy の wheel
