- name: Toolchain & deps (fix)
  shell: bash -l {0}
  run: |
    # （任意）確認用
    conda info
    which python
    python -V

    # Fortran は保険（wfnsympy 等をソースビルドする場合に備えて）
    mamba install -y fortran-compiler pip

    # ★ ここが肝：pip で numpy<2 と setuptools<60 を先に"必ず"入れる
    python -m pip install -U "numpy<2" "scipy==1.10.1" "setuptools<60"

    # huckelpy は古い build 系なので build isolation を切って numpy を使わせる
    python -m pip install --no-build-isolation "huckelpy==0.2.3"

    # cosymlib 本体（cp310 の wheel があるのでソースビルドに行かない）
    #    wheelだけ使いたい場合は --only-binary=:all: を付けてもOK
    python -m pip install -U "cosymlib==0.11.1"

    # GUI / パッカー
    python -m pip install -U "flet[all]==0.28.3" pyinstaller
