name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pipx install uv

      - name: Sync deps
        run: uv sync --python 3.11

      - name: Pack with Flet (PyInstaller)
        run: |
          uv run python -m pip install -U flet pyinstaller
          uv run flet pack src/shape_measure/gui.py --name "Easy Shape"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: easy-shape-windows
          path: dist/**
