name: Release EXE

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pipx install uv
      - run: uv sync --python 3.11
      - run: uv run python -m pip install -U "flet[all]==0.28.3" pyinstaller
      - run: uv run flet pack src/shape_measure/gui.py --name "Easy Shape"
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**
