name: Release EXE

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"      # ← 3.10 に固定（cp310 wheelを使う）

      - name: Install build tools
        run: |
          python -m pip install -U pip
          # 先にnumpyを入れて古い依存のメタ生成を安定化
          python -m pip install -U "numpy<2" "setuptools<60"
          # huckelpy は古い build 系なので build isolation を切っておくと安定
          python -m pip install --no-build-isolation "huckelpy==0.2.3"
          # cosymlib本体は wheel を使わせたいので only-binary 指定
          python -m pip install --only-binary=:all: "cosymlib==0.11.1"
          # GUI/パッカー
          python -m pip install -U "flet[all]==0.28.3" pyinstaller

      - name: Pack with Flet (PyInstaller)
        run: |
          python -m flet pack src/shape_measure/gui.py --name "Easy Shape" --icon assets/icon.ico

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**
